---
kind: Service
apiVersion: v1
metadata:
  name: bb-service
spec:
  selector:
    app: bb-app
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bb-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bb-app
    spec:
      containers:
        - name: bb
          image: bootcamp-big-brother:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: localhost
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: bb_user
            - name: POSTGRES_PASSWORD
              value: pswd