version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bb_user
      POSTGRES_PASSWORD: pswd
    ports:
      - "5432:5432"
  app:
    image: default/bootcamp-big-brother
    depends_on:
      - db
    ports:
      - "9001:9001"